// adlaan-app/src/app/features/auth/signup/signup.component.ts
import { Component, inject, effect, ChangeDetectionStrategy, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule, FormGroup, Validators, FormControl } from '@angular/forms';
import { Router } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { AuthService } from '../../../core';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule],
  templateUrl: './signup.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SignupComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  // Signal-based reactive state
  protected isLoading = signal(false);
  protected errorMessage = signal('');
  protected showPassword = signal(false);
  protected agreeToTerms = signal(false);

  // Modern Angular 20+ pattern: Reactive Forms with Signal integration
  protected signupForm = new FormGroup({
    name: new FormControl('', [Validators.required, Validators.minLength(2)]),
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(8)])
  });

  // Signal integration with reactive forms (Angular 20+ pattern)
  protected formValue = toSignal(this.signupForm.valueChanges, { initialValue: this.signupForm.value });
  protected isFormValid = computed(() => this.signupForm.valid && this.agreeToTerms());

  constructor() {
    // Use effect for modern signal-based reactivity
    effect(() => {
      const currentUser = this.authService.currentUser();
      const isInitialized = this.authService.isAuthInitializedComputed();
      
      if (currentUser && isInitialized) {
        this.router.navigate(['/'], { replaceUrl: true });
      }
    });
  }

  
  togglePasswordVisibility(): void {
    this.showPassword.set(!this.showPassword());
  }

  onSubmit(): void {
    // Mark all fields as touched to show validation errors
    this.signupForm.markAllAsTouched();
    
    if (this.signupForm.valid && this.agreeToTerms()) {
      this.isLoading.set(true);
      this.errorMessage.set('');

      const signupData = {
        name: this.signupForm.value.name,
        email: this.signupForm.value.email,
        password: this.signupForm.value.password
      };

      console.log('Sending signup request with:', signupData);

      this.authService.register(signupData).subscribe({
        next: (response) => {
          console.log('Signup response:', response);
          this.isLoading.set(false);

          if (response.requiresEmailVerification) {
            // Handle email verification scenario
            console.log('Email verification required');
            this.errorMessage.set('Please check your email to verify your account before signing in.');
          } else if (response.user) {
            // Successful signup without email verification
            console.log('Signup successful, redirecting to home');
            this.router.navigate(['/']);
          } else {
            this.errorMessage.set('Signup response received but no user data found.');
          }
        },
        error: (error: any) => {
          console.error('Signup error:', error);
          this.isLoading.set(false);
          
          // Handle different types of errors
          if (error.status === 409) {
            this.errorMessage.set('An account with this email already exists. Please try signing in instead.');
          } else if (error.status === 422) {
            this.errorMessage.set('Please check your information and try again.');
          } else if (error.status === 429) {
            this.errorMessage.set('Too many signup attempts. Please try again later.');
          } else if (error.status === 500) {
            this.errorMessage.set('Server error. Please try again later.');
          } else {
            this.errorMessage.set(error.error?.message || 'Signup failed. Please try again.');
          }
        }
      });
    } else if (!this.agreeToTerms()) {
      this.errorMessage.set('Please agree to the Terms of Service and Privacy Policy.');
    } else {
      console.log('Form is invalid:', this.signupForm.errors);
      this.errorMessage.set('Please fill in all required fields correctly.');
    }
  }

  onGoogleSignUp(): void {
    // TODO: Implement Google OAuth integration
    console.log('Google sign-up clicked');
    // Placeholder for Google OAuth implementation
  }

  onSignIn(): void {
    this.router.navigate(['/login']);
  }

  onContactSales(): void {
    // TODO: Open contact sales modal or navigate to contact page
    console.log('Contact sales clicked');
    // window.open('mailto:sales@adlaan.com', '_blank');
  }
}

<!-- Professional Split Layout Container -->
<main class="flex h-screen w-screen bg-white font-inter fixed inset-0" role="main">
  <!-- Left Panel - Dark Professional -->
  <aside class="w-full lg:w-1/2 bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 flex flex-col justify-center relative overflow-hidden shadow-2xl" role="complementary" aria-label="Brand information">
    <!-- Enhanced background pattern -->
    <div class="absolute inset-0 opacity-10">
      <div class="absolute inset-0" style="background-image: radial-gradient(circle at 2px 2px, rgba(255,255,255,0.4) 1px, transparent 0); background-size: 32px 32px;"></div>
    </div>
    
    <!-- Subtle gradient overlay -->
    <div class="absolute inset-0 bg-gradient-to-br from-transparent via-gray-800/20 to-gray-900/40"></div>
    
    <!-- Content -->
    <div class="relative z-10 px-8 lg:px-12 max-w-md mx-auto lg:mx-0">
      <!-- Logo -->
      <header class="mb-8 transform transition-all duration-700 ease-out">
        <h1 class="text-4xl lg:text-3xl font-bold mb-2 tracking-tight bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent">Adlaan</h1>
        <p class="text-gray-300 text-sm font-medium tracking-wide">Legal AI Platform</p>
      </header>

      <!-- Tagline -->
      <div class="mb-12 transform transition-all duration-700 ease-out delay-300">
        <h2 class="text-2xl lg:text-xl font-semibold text-white mb-4 leading-tight">
          Join the future of legal practice
        </h2>
        <p class="text-gray-300 text-base lg:text-sm leading-relaxed">
          Get started with AI-powered legal document analysis and unlock the potential of your practice.
        </p>
      </div>

      <!-- Key Features -->
      <div class="space-y-8 lg:space-y-6">
        <div class="flex items-start space-x-4 transform transition-all duration-500 ease-out delay-500 hover:translate-x-2">
          <div class="w-3 h-3 bg-gradient-to-r from-gray-400 to-gray-300 rounded-full mt-2 flex-shrink-0 shadow-lg"></div>
          <div>
            <h4 class="text-white text-base lg:text-sm font-semibold mb-2">Free 14-Day Trial</h4>
            <p class="text-gray-300 text-sm lg:text-xs leading-relaxed">No credit card required. Full access to all features</p>
          </div>
        </div>
        
        <div class="flex items-start space-x-4 transform transition-all duration-500 ease-out delay-700 hover:translate-x-2">
          <div class="w-3 h-3 bg-gradient-to-r from-gray-400 to-gray-300 rounded-full mt-2 flex-shrink-0 shadow-lg"></div>
          <div>
            <h4 class="text-white text-base lg:text-sm font-semibold mb-2">Instant Setup</h4>
            <p class="text-gray-300 text-sm lg:text-xs leading-relaxed">Get up and running in less than 5 minutes</p>
          </div>
        </div>
        
        <div class="flex items-start space-x-4 transform transition-all duration-500 ease-out delay-900 hover:translate-x-2">
          <div class="w-3 h-3 bg-gradient-to-r from-gray-400 to-gray-300 rounded-full mt-2 flex-shrink-0 shadow-lg"></div>
          <div>
            <h4 class="text-gray-50 text-base lg:text-sm font-semibold mb-2">Expert Support</h4>
            <p class="text-gray-300 text-sm lg:text-xs leading-relaxed">24/7 customer support from legal tech experts</p>
          </div>
        </div>
      </div>
    </div>
  </aside>
  
  <!-- Right Panel - Clean Light Interface -->
  <div class="w-full lg:w-1/2 bg-white flex items-center justify-center px-6 lg:px-8 min-h-screen lg:min-h-0">
    <div class="w-full max-w-md">
      <!-- Header -->
      <div class="text-center mb-8 transform transition-all duration-700 ease-out">
        <h2 class="text-3xl lg:text-2xl font-bold text-gray-900 mb-3">Create your account</h2>
        <p class="text-gray-600 text-base lg:text-sm">Start your 14-day free trial today</p>
      </div>
      
      <!-- Form -->
      <form [formGroup]="signupForm" (ngSubmit)="onSubmit()" class="space-y-6 transform transition-all duration-700 ease-out delay-300" role="form" aria-label="Sign up form">
        <!-- Name Field -->
        <div class="space-y-2">
          <label for="name" class="block text-sm font-semibold text-gray-800">
            Full name <span class="text-red-500" aria-label="required">*</span>
          </label>
          <div class="relative group">
            <input
              type="text"
              id="name"
              formControlName="name"
              placeholder="Enter your full name"
              class="w-full h-12 px-4 pr-12 border-2 border-gray-200 rounded-lg bg-white focus:border-gray-400 focus:ring-4 focus:ring-gray-100 transition-all duration-300 text-sm font-medium shadow-sm hover:shadow-md focus:shadow-lg"
              [class.border-red-400]="signupForm.get('name')?.invalid && signupForm.get('name')?.touched"
              [class.border-gray-400]="signupForm.get('name')?.valid && signupForm.get('name')?.touched"
              [class.bg-red-50]="signupForm.get('name')?.invalid && signupForm.get('name')?.touched"
              [class.bg-gray-50]="signupForm.get('name')?.valid && signupForm.get('name')?.touched"
              [attr.aria-invalid]="signupForm.get('name')?.invalid && signupForm.get('name')?.touched"
              [attr.aria-describedby]="signupForm.get('name')?.invalid && signupForm.get('name')?.touched ? 'name-error' : null"
              autocomplete="name"
              required />
            <!-- Valid Name Icon -->
            <div *ngIf="signupForm.get('name')?.valid && signupForm.get('name')?.touched" 
                 class="absolute right-4 top-1/2 transform -translate-y-1/2 transition-all duration-300"
                 role="img" aria-label="Valid name">
              <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M5 13l4 4L19 7"></path>
              </svg>
            </div>
            <!-- Invalid Name Icon -->
            <div *ngIf="signupForm.get('name')?.invalid && signupForm.get('name')?.touched" 
                 class="absolute right-4 top-1/2 transform -translate-y-1/2 transition-all duration-300"
                 role="img" aria-label="Invalid name">
              <svg class="w-5 h-5 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
            </div>
          </div>
          <div 
            *ngIf="signupForm.get('name')?.invalid && signupForm.get('name')?.touched"
            class="text-sm text-red-600 flex items-center space-x-1 animate-pulse"
            id="name-error"
            role="alert"
          >
            <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
            </svg>
            <span>Please enter your full name (at least 2 characters)</span>
          </div>
        </div>

        <!-- Email Field -->
        <div class="space-y-2">
          <label for="email" class="block text-sm font-semibold text-gray-800">
            Email address <span class="text-red-500" aria-label="required">*</span>
          </label>
          <div class="relative group">
            <input
              type="email"
              id="email"
              formControlName="email"
              placeholder="Enter your email address"
              class="w-full h-12 px-4 pr-12 border-2 border-gray-200 rounded-lg bg-white focus:border-gray-400 focus:ring-4 focus:ring-gray-100 transition-all duration-300 text-sm font-medium shadow-sm hover:shadow-md focus:shadow-lg"
              [class.border-red-400]="signupForm.get('email')?.invalid && signupForm.get('email')?.touched"
              [class.border-gray-400]="signupForm.get('email')?.valid && signupForm.get('email')?.touched"
              [class.bg-red-50]="signupForm.get('email')?.invalid && signupForm.get('email')?.touched"
              [class.bg-gray-50]="signupForm.get('email')?.valid && signupForm.get('email')?.touched"
              [attr.aria-invalid]="signupForm.get('email')?.invalid && signupForm.get('email')?.touched"
              [attr.aria-describedby]="signupForm.get('email')?.invalid && signupForm.get('email')?.touched ? 'email-error' : null"
              autocomplete="email"
              required />
            <!-- Valid Email Icon -->
            <div *ngIf="signupForm.get('email')?.valid && signupForm.get('email')?.touched" 
                 class="absolute right-4 top-1/2 transform -translate-y-1/2 transition-all duration-300"
                 role="img" aria-label="Valid email">
              <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M5 13l4 4L19 7"></path>
              </svg>
            </div>
            <!-- Invalid Email Icon -->
            <div *ngIf="signupForm.get('email')?.invalid && signupForm.get('email')?.touched" 
                 class="absolute right-4 top-1/2 transform -translate-y-1/2 transition-all duration-300"
                 role="img" aria-label="Invalid email">
              <svg class="w-5 h-5 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
              </svg>
            </div>
          </div>
          <div 
            *ngIf="signupForm.get('email')?.invalid && signupForm.get('email')?.touched"
            class="text-sm text-red-600 flex items-center space-x-1 animate-pulse"
            id="email-error"
            role="alert"
          >
            <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
            </svg>
            <span>Please enter a valid email address</span>
          </div>
        </div>

        <!-- Password Field -->
        <div class="space-y-2">
          <label for="password" class="block text-sm font-semibold text-gray-800">
            Password <span class="text-red-500" aria-label="required">*</span>
          </label>
          <div class="relative group">
            <input
              [type]="showPassword() ? 'text' : 'password'"
              id="password"
              formControlName="password"
              placeholder="Create a strong password"
              class="w-full h-12 px-4 pr-12 border-2 border-gray-200 rounded-lg bg-white focus:border-gray-400 focus:ring-4 focus:ring-gray-100 transition-all duration-300 text-sm font-medium shadow-sm hover:shadow-md focus:shadow-lg"
              [class.border-red-400]="signupForm.get('password')?.invalid && signupForm.get('password')?.touched"
              [class.border-gray-400]="signupForm.get('password')?.valid && signupForm.get('password')?.touched"
              [class.bg-red-50]="signupForm.get('password')?.invalid && signupForm.get('password')?.touched"
              [class.bg-gray-50]="signupForm.get('password')?.valid && signupForm.get('password')?.touched"
              [attr.aria-invalid]="signupForm.get('password')?.invalid && signupForm.get('password')?.touched" 
              [attr.aria-describedby]="signupForm.get('password')?.invalid && signupForm.get('password')?.touched ? 'password-error' : null"
              autocomplete="new-password"
              required />
            <!-- Password Visibility Toggle -->
            <button 
              type="button" 
              class="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-500 hover:text-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-300 focus:ring-offset-2 rounded-md p-1 transition-all duration-200"
              (click)="togglePasswordVisibility()"
              [attr.aria-label]="showPassword() ? 'Hide password' : 'Show password'"
              tabindex="0">
              <svg *ngIf="!showPassword()" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
              </svg>
              <svg *ngIf="showPassword()" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"></path>
              </svg>
            </button>
          </div>
          <div 
            *ngIf="signupForm.get('password')?.invalid && signupForm.get('password')?.touched"
            class="text-sm text-red-600 flex items-center space-x-1 animate-pulse"
            id="password-error"
            role="alert"
          >
            <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
            </svg>
            <span>Password must be at least 8 characters long</span>
          </div>
        </div>

        <!-- Terms Agreement -->
        <div class="flex items-start space-x-3 pt-2">
          <input 
            type="checkbox" 
            id="agreeToTerms" 
            [ngModel]="agreeToTerms()" (ngModelChange)="agreeToTerms.set($event)" 
            [ngModelOptions]="{standalone: true}"
            class="h-4 w-4 text-gray-600 border-gray-300 rounded focus:ring-gray-400 focus:ring-2 focus:ring-offset-2 transition-all duration-200 cursor-pointer mt-1" 
            aria-describedby="terms-description" />
          <label for="agreeToTerms" class="text-sm text-gray-700 cursor-pointer select-none leading-relaxed">
            I agree to the 
            <a href="#" class="font-medium text-gray-800 hover:text-gray-900 underline">Terms of Service</a> 
            and 
            <a href="#" class="font-medium text-gray-800 hover:text-gray-900 underline">Privacy Policy</a>
          </label>
        </div>

        <!-- Submit Button -->
        <button 
          type="submit" 
          class="w-full h-12 bg-gradient-to-r from-gray-800 to-gray-900 hover:from-gray-900 hover:to-black text-white font-semibold rounded-lg transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center shadow-lg hover:shadow-xl focus:outline-none focus:ring-4 focus:ring-gray-300 focus:ring-offset-2 transform hover:scale-[1.02] active:scale-[0.98]"
          [disabled]="signupForm.invalid || !agreeToTerms() || isLoading()"
          [attr.aria-label]="isLoading() ? 'Creating account, please wait' : 'Create your account'"
        >
          <span *ngIf="!isLoading()" class="flex items-center space-x-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z"></path>
            </svg>
            <span>Create Account</span>
          </span>
          <div *ngIf="isLoading()" class="flex items-center space-x-3">
            <div class="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
            <span>Creating account...</span>
          </div>
        </button>

        <!-- Error Message -->
        <div 
          *ngIf="errorMessage"
          class="text-sm text-red-700 text-center bg-red-50 border-2 border-red-200 rounded-lg p-4 shadow-sm animate-pulse"
          role="alert"
          aria-live="polite"
        >
          <div class="flex items-center justify-center space-x-2">
            <svg class="w-5 h-5 text-red-600" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
            </svg>
            <span class="font-medium">{{ errorMessage() }}</span>
          </div>
        </div>
      </form>

      <!-- Divider -->
      <div class="my-8 relative">
        <div class="absolute inset-0 flex items-center">
          <div class="w-full border-t-2 border-gray-200"></div>
        </div>
        <div class="relative flex justify-center text-sm">
          <span class="px-4 bg-white text-gray-500 font-medium">or continue with</span>
        </div>
      </div>

      <!-- Google Sign Up -->
      <button 
        type="button"
        (click)="onGoogleSignUp()"
        class="w-full h-12 bg-white border-2 border-gray-200 hover:border-gray-300 hover:shadow-lg text-gray-700 font-semibold rounded-lg transition-all duration-300 flex items-center justify-center mb-8 shadow-sm focus:outline-none focus:ring-4 focus:ring-gray-200 focus:ring-offset-2 transform hover:scale-[1.02] active:scale-[0.98]"
        aria-label="Sign up with Google"
      >
        <svg class="w-5 h-5 mr-3" viewBox="0 0 24 24" aria-hidden="true">
          <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
          <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
          <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
          <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
        </svg>
        <span>Continue with Google</span>
      </button>

      <!-- Sign In Link -->
      <div class="text-center">
        <p class="text-sm text-gray-600 mb-4">
          Already have an account? 
          <a href="#" 
             (click)="onSignIn()"
             class="font-semibold text-gray-800 hover:text-gray-900 focus:outline-none focus:underline focus:ring-2 focus:ring-gray-300 focus:ring-offset-2 rounded-md px-1 py-1 transition-all duration-200"
             tabindex="0">
            Sign in here
          </a>
        </p>
        <p class="text-xs text-gray-500">
          Questions? 
          <a href="#" 
             (click)="onContactSales()"
             class="text-gray-600 hover:text-gray-800 underline"
             tabindex="0">
            Contact our team
          </a>
        </p>
      </div>

      <!-- Footer -->
      <footer class="text-center mt-8">
        <p class="text-xs text-gray-500 flex items-center justify-center space-x-1">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"></path>
          </svg>
          <span>Secured by enterprise-grade encryption</span>
        </p>
      </footer>
    </div>
  </div>
</main>

// adlaan-front/src/app/signup/page.tsx
"use client";

import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { ArrowLeft, Mail, Lock, User } from "lucide-react";
import Link from "next/link";
import { useState, FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "../../contexts/AuthContext";

export default function SignUpPage() {
  const router = useRouter();
  const { signup } = useAuth();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [agreedToTerms, setAgreedToTerms] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError("");
    setIsLoading(true);

    // Validation
    if (!name || !email || !password) {
      setError("Please fill in all fields");
      setIsLoading(false);
      return;
    }

    if (name.trim().length < 2) {
      setError("Name must be at least 2 characters");
      setIsLoading(false);
      return;
    }

    if (!email.includes("@")) {
      setError("Please enter a valid email address");
      setIsLoading(false);
      return;
    }

    if (password.length < 8) {
      setError("Password must be at least 8 characters");
      setIsLoading(false);
      return;
    }

    if (!agreedToTerms) {
      setError("Please agree to the Terms of Service and Privacy Policy");
      setIsLoading(false);
      return;
    }

    try {
      console.log('Attempting signup with:', { name, email, password: '***' });
      // Call the GraphQL signup mutation with ADMIN role
      await signup(name, email, password, "ADMIN");
      console.log('Signup successful');

      setSuccess(true);

      setSuccess(true);

      // Redirect to company setup page after successful registration
      setTimeout(() => {
        router.push("/company-setup");
      }, 1500);

    } catch (err: unknown) {
      console.error('Signup error:', err);
      const error = err as Error;
      setError(error.message || "Failed to create account. Please try again.");
      setIsLoading(false);
    }
  };

  const handleSocialSignup = (provider: string) => {
    setIsLoading(true);
    // Implement social signup logic here
    console.log(`${provider} signup clicked`);
    setTimeout(() => setIsLoading(false), 1000);
  };

  return (
    <div className="min-h-screen bg-black flex items-center justify-center px-6 py-12 relative overflow-hidden">
      {/* Background pattern */}
      <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGRlZnM+PHBhdHRlcm4gaWQ9ImdyaWQiIHdpZHRoPSI2MCIgaGVpZ2h0PSI2MCIgcGF0dGVyblVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHBhdGggZD0iTSAxMCAwIEwgMCAwIDAgMTAiIGZpbGw9Im5vbmUiIHN0cm9rZT0icmdiYSgyNTUsIDI1NSwgMjU1LCAwLjAzKSIgc3Ryb2tlLXdpZHRoPSIxIi8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ1cmwoI2dyaWQpIi8+PC9zdmc+')] opacity-40"></div>
      
      <div className="w-full max-w-md relative z-10">
        {/* Back button */}
        <Link href="/" className="inline-flex items-center gap-2 text-gray-400 hover:text-white transition-colors mb-8">
          <ArrowLeft className="h-4 w-4" />
          <span className="text-sm">Back to home</span>
        </Link>

        <Card className="bg-zinc-900 border border-white/10 rounded-2xl">
          <CardHeader className="text-center pb-8">
            {/* Logo */}
            <div className="flex justify-center mb-6">
              <div className="h-12 w-12 rounded-xl bg-white flex items-center justify-center">
                <span className="text-black font-bold text-lg">A</span>
              </div>
            </div>
            
            <CardTitle className="text-3xl font-bold text-white mb-2">
              Create your account
            </CardTitle>
            <CardDescription className="text-gray-400 text-base">
              Start your 14-day free trial
            </CardDescription>
          </CardHeader>

          <CardContent className="space-y-6">
            {/* Success Message */}
            {success && (
              <div className="p-3 bg-green-500/10 border border-green-500/20 rounded-lg">
                <p className="text-sm text-green-400">Account created successfully! Redirecting to sign in...</p>
              </div>
            )}

            {/* Error Message */}
            {error && (
              <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
                <p className="text-sm text-red-400">{error}</p>
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Name Input */}
              <div className="space-y-2">
                <label htmlFor="name" className="text-sm font-medium text-white">
                  Full name
                </label>
                <div className="relative">
                  <User className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                  <input
                    id="name"
                    type="text"
                    placeholder="John Doe"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    disabled={isLoading}
                    className="w-full pl-10 pr-4 py-3 bg-black border border-white/10 rounded-lg text-white placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-white/20 focus:border-white/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                </div>
              </div>

              {/* Email Input */}
              <div className="space-y-2">
                <label htmlFor="email" className="text-sm font-medium text-white">
                  Email address
                </label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                  <input
                    id="email"
                    type="email"
                    placeholder="you@example.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    disabled={isLoading}
                    className="w-full pl-10 pr-4 py-3 bg-black border border-white/10 rounded-lg text-white placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-white/20 focus:border-white/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                </div>
              </div>

              {/* Password Input */}
              <div className="space-y-2">
                <label htmlFor="password" className="text-sm font-medium text-white">
                  Password
                </label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                  <input
                    id="password"
                    type="password"
                    placeholder="Create a password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    disabled={isLoading}
                    className="w-full pl-10 pr-4 py-3 bg-black border border-white/10 rounded-lg text-white placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-white/20 focus:border-white/30 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                </div>
                <p className="text-xs text-gray-500">Must be at least 8 characters</p>
              </div>

              {/* Terms checkbox */}
              <div className="flex items-start">
                <input
                  id="terms"
                  type="checkbox"
                  checked={agreedToTerms}
                  onChange={(e) => setAgreedToTerms(e.target.checked)}
                  disabled={isLoading}
                  className="h-4 w-4 mt-0.5 rounded border-white/10 bg-black text-white focus:ring-2 focus:ring-white/20 disabled:opacity-50"
                />
                <label htmlFor="terms" className="ml-2 text-sm text-gray-400">
                  I agree to the{" "}
                  <Link href="/terms" className="text-white hover:underline">
                    Terms of Service
                  </Link>{" "}
                  and{" "}
                  <Link href="/privacy" className="text-white hover:underline">
                    Privacy Policy
                  </Link>
                </label>
              </div>

              {/* Sign up button */}
              <Button
                type="submit"
                size="lg"
                disabled={isLoading}
                className="w-full bg-white text-black hover:bg-gray-100 font-semibold py-6 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isLoading ? "Creating account..." : "Create account"}
              </Button>
            </form>

            {/* Divider */}
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-white/10"></div>
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-2 bg-zinc-900 text-gray-400">Or sign up with</span>
              </div>
            </div>

            {/* Social signup buttons */}
            <div className="grid grid-cols-2 gap-3">
              <Button
                type="button"
                variant="outline"
                onClick={() => handleSocialSignup("Google")}
                disabled={isLoading}
                className="bg-black border border-white/10 text-white hover:bg-white/5 hover:border-white/20 py-6 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <svg className="h-5 w-5 mr-2" viewBox="0 0 24 24">
                  <path
                    fill="currentColor"
                    d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                  />
                  <path
                    fill="currentColor"
                    d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                  />
                  <path
                    fill="currentColor"
                    d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                  />
                  <path
                    fill="currentColor"
                    d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                  />
                </svg>
                Google
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={() => handleSocialSignup("GitHub")}
                disabled={isLoading}
                className="bg-black border border-white/10 text-white hover:bg-white/5 hover:border-white/20 py-6 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <svg className="h-5 w-5 mr-2" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                </svg>
                GitHub
              </Button>
            </div>

            {/* Sign in link */}
            <div className="text-center text-sm text-gray-400">
              Already have an account?{" "}
              <Link href="/signin" className="text-white hover:underline font-medium">
                Sign in
              </Link>
            </div>
          </CardContent>
        </Card>

        {/* Footer */}
        <p className="text-center text-sm text-gray-500 mt-8">
          © 2025 Adlaan Inc. All rights reserved.
        </p>
      </div>
    </div>
  );
}
